### ISSUE TITLE
unit scale / conversion 

### ISSUE THREAD

**Issue by species5618** [bellrichm/WeeWX-MQTTSubscribe#42]
loving this driver BTW

unless I am doing something stupid , I cant see a way to do unit conversion / scaling when processing incoming data

I have mastered the labels, and that is working great.

but would like to convert the scale of units during processing
using RTL_433 the bresser 5 in 1 outputs 

'rain' is mm, weewx wants cm ( * 0.1)
'windSpeed'    is m/s, weewx wants km/h (* 3.6)
'windGust'    is m/s, weewx wants km/h (* 3.6)

**Comment by bellrichm** [comment]
Hi,
Thanks for giving it a try. I am not a units expert, but based on this, http://www.weewx.com/docs/customizing.htm#units it sounds like your incoming data is METRICWX and your database is METRIC. So this should accomplish what you want.
```
[[topics]]
unit_system = METRICWX
[[[topic to subscribe to]]]
```
- rich

**Comment by species5618** [comment]
i think METRICWX would fix the rain, (many thanks for the contains total update) but not wind speed

data source is RTL_433 extracting data from a Bresser 5in1, 
i have applied a work around by compiling my own device handler and doing the maths  there. 

Probably makes more sense,

**Comment by bellrichm** [comment]
Glad you have something working. This is why I thought METRICWX might work for both. 
METRICWX | 0x11 | Metric, with rain related measurements in mm and **speeds in m/s**
METRIC | 0x10 | Metric, with rain related measurements in cm and **speeds in km/hr**

The other thought I had was WeeWX StdCalibrate, http://www.weewx.com/docs/usersguide.htm#StdCalibrate

Have you tried the new contains total code in MQTTSubscribe? I just want to add some more debug logging before packaging a release.

Since I think you are all set, I am going to close this issue. Feel free to reopen.
- rich

**Comment by species5618** [comment]
yes i am running the contains_total option

as i am getting raw sensor counter data , not station data

just waiting for some Rain !
