### ISSUE TITLE
Wind data is not being ‘collected’ across MQTT payloads

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#44]
From my understanding of how WeeWX handles wind data, the loop packet has to have the windSpeed along with the windDir. If it doesn’t, the windDir will be ignored. 
Code was developed to collect the wind data across multiple MQTT payloads into a single loop packet. But due to a bug, it was never called.
In addition, the code attempted to handle multiple data fields in a MQTT payload. The code has been simplified to only work with ‘individual’ payloads, with the assumption that payloads with multiple fields should have the necessary data in the payload.

**Comment by bellrichm** [comment]
@sussex1
I think I have this fixed. It passes the unit tests, but I don’t have functional tests yet.  A prerelease is here https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v1.5.0-rc02
If you could give it a try and let me know how it goes, that would be greatly appreciated. If you run into problems, attaching the log is appreciated.
Thanks for your help! Rich

**Comment by sussex1** [comment]
rich
Do I need to make any changes to weewx.config?  windDir is no longer showing in the record packets and windRaw is appearing in the loop and record packets so I assume label_map is no longer working.
Ian


`LOOP:   2020-01-23 15:55:13 AEDT (1579755313) dateTime: 1579755313.01, maxSolarRad: None, outTemp: 39.37, rainRate: 24.072, usUnits: 17
LOOP:   2020-01-23 15:55:13 AEDT (1579755313) dateTime: 1579755313.04, maxSolarRad: None, outHumidity: 21.52, rainRate: 24.072, usUnits: 17
LOOP:   2020-01-23 15:55:13 AEDT (1579755313) dateTime: 1579755313.05, maxSolarRad: None, rainRate: 24.072, usUnits: 17, windDir: 331.0
LOOP:   2020-01-23 15:55:13 AEDT (1579755313) dateTime: 1579755313.05, maxSolarRad: None, rain: 0.034, rainRate: 24.208, usUnits: 17
LOOP:   2020-01-23 15:55:13 AEDT (1579755313) dateTime: 1579755313.05, maxSolarRad: None, rainRate: 24.208, usUnits: 17, windRaw: 66.0
LOOP:   2020-01-23 15:55:17 AEDT (1579755317) bmp_temp: 40.1, dateTime: 1579755317.92, maxSolarRad: None, rainRate: 24.208, usUnits: 17
REC:    2020-01-23 15:55:00 AEDT (1579755300) baro_mb: 995.184, bmp_temp: 40.3316666667, cloudbase: 3291.1497146, dateTime: 1579755300.0, dewpoint: 13.2052561403, ET: None, heatindex: 39.5516666667, humidex: 42.4619539575, interval: 5, maxSolarRad: None, outHumidity: 21.1243333333, outTemp: 39.5516666667, rain: 2.04, rainRate: 24.208, usUnits: 17, windRaw: 111.65
`

**Comment by bellrichm** [comment]
Ian,
Although I am phasing out label_map, it should still work. In rc 03 I fixed a bug such that the label_map would not work if you had something like this
```
[[[label_map]]]
    windRaw = windSpeed

[[[fields]]]
    [[[[windRaw]]]]
       conversion_type = float
```

But, I also think you have a typo in the config you posted. The windRaw is missing a ']'
```
[[[[windRaw]]]
```

Using just fields, this should essentially be what you want
```
[[[fields]]]
    [[[[windRaw]]]]
        name = windSpeed
    [[[[baro_mb]]]]
        name = barometer
    [[[[rainTotal]]]]
        name = rain # I didn't check what the WeeWX name really is
        contains_total = True
```

I really appreciate all of your help. -rich

**Comment by sussex1** [comment]
Thanks rich
The extra ] was a big help ;) the fields are mapping properly . 
Going by the log output cumulative rain is working but is 3am here so am not going out to spray water on the roof mounted rain gauge  hihi.
There is wind blowing atm but windDir is still not making it through to the archive records, not sure if you had a fix for that in rc3.
Ian

**Comment by bellrichm** [comment]
Ian,
Drat, I thought I had fixed the windDir bug. Could you post the log with rc03 and the MQTTSubscribe config section?
Thanks. - rich

**Comment by bellrichm** [comment]
Ian,
On second thought, hold off. I think I want to revamp the handling of wind data to make it more robust. And if you are up for testing the new implementation, that would be a big help.
- rich

**Comment by bellrichm** [comment]
Darn. I thought i could leverage the WeeWX accumulator for the wind data. But, it expects the wind data to be together - the whole reason I wrote the Collector in the first place....

**Comment by sussex1** [comment]
Ok you write it and ill test it. I have looked through the code and is well beyond my python abilities so cant contribute  to that.

**Comment by sussex1** [comment]
It's simple unough for me to update my ESP8266 code to output in JSON format and avoid the whole individual records rabbit hole. Probably should have done that in the first place but the library I used then didn't like long strings and I wasn't publishing wind direction at the time.Anyway I'm happy to test the code if u continue with changes for individual wind dataIanSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Rich Bell <notifications@github.com> Date: 24/01/2020  12:21  (GMT+10:00) To: bellrichm/WeeWX-MQTTSubscribe <WeeWX-MQTTSubscribe@noreply.github.com> Cc: sussex1 <ieand@our.id.au>, Mention <mention@noreply.github.com> Subject: Re: [bellrichm/WeeWX-MQTTSubscribe] Wind data is not being ‘collected’ across MQTT payloads (#44) Darn. I thought i could leverage the WeeWX accumulator for the wind data. But, it expects the wind data to be together - the whole reason I wrote the Collector in the first place....

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bellrichm/WeeWX-MQTTSubscribe/issues/44?email_source=notifications\u0026email_token=AEJW6UNOJKQ4MKTT6B5VAV3Q7I7BXA5CNFSM4KKGPLS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJZN2VY#issuecomment-577953111",
"url": "https://github.com/bellrichm/WeeWX-MQTTSubscribe/issues/44?email_source=notifications\u0026email_token=AEJW6UNOJKQ4MKTT6B5VAV3Q7I7BXA5CNFSM4KKGPLS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJZN2VY#issuecomment-577953111",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bellrichm** [comment]
Ian, 
If you are up for a bit more testing, I’d like to get the individual record windDir working. Turns out my approach in rc03 seems to be the best. This should put windSpeed and WindDir in the same loop packet. It works in my test, but that is not real world. Could you try and pos the log? No hurry, I have some other things that I need to do in the next couple of days.
And yeah, it is probably a bit over engineered (meaning complicated), but my goal was/is a service and driver that could handle many different MQTT formats.  And even more, a chance to really learn WeeWX and MQTT.
Thanks. rich

**Comment by sussex1** [comment]
rich
No worries.  here is the logs
ian
[weewx_log_100026012020.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4113025/weewx_log_100026012020.txt)

**Comment by bellrichm** [comment]
Ian,
In weewx_log_100026012020.txt at line 417, it looks like it was running with rc01 to me.  Could you double check? If it is easier to just grab from master that is fine for this test.
Thanks. rich

**Comment by sussex1** [comment]
rich
OOps You are right, must have filezillered the wrong one over.  Got a new copy from master loaded now but the arduino that publishes is in the bench to sort out some extra rain gauge tips, probably RF getting in so decoupling caps may fix. Will get it all back together later today hopefully.
Ian

**Comment by bellrichm** [comment]
Ian,
No worries.  Believe me, I get it.
No hurry. Again, thanks for your help.  - rich

**Comment by sussex1** [comment]
rich
Have put the publisher back on the roof temporarily. From what i can see rc04 looks to be doing exactly what it should with the windDir and rainTotals, thanks for the help.
Hopefully 1 more bug squashed;). Log attached
ian
[weewx_log_150729012020.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4126152/weewx_log_150729012020.txt)

**Comment by bellrichm** [comment]
Ian,
It looks good to me. Once I wrap up some test prototyping , I’ll package it up in a 1.5.0 release.
Thanks for your help in testing and debugging. - rich
